Documentation:
  Enabled: false
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GuardClause:
  MinBodyLength: 15
Naming/FileName:
  Enabled: false
Metrics/BlockLength:
  CountComments: false
  Max: 25
  ExcludedMethods: ['describe', 'context', 'feature']
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
Metrics/MethodLength:
  CountComments: false
  Max: 15
Metrics/AbcSize:
  Max: 18
Metrics/ParameterLists:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '**/Rakefile'
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
